add xSushiFeed
InverseFinance/anchor pull request #3
Opened 2021-04-01 13:49 UTC by nourharidy

`XSushiFeed` uses Chainlink SUSHI/ETH and ETH/USD feeds to determine SUSHI/USD price and coverts it to XSUSHI price using `XSushiExchangeRate` contract.

`XSushiFeed` inherits the Chainlink interface and is meant to mimic a XSUSHI/USD Chainlink feed to be added to Anchor's `Oracle` contract by governance using `setFeed` function.

Mainnet Deployment: `0x8Aa3932790b33C7Cc751231161Ae5221af058D12`
Anchor oracle: `0xE8929AFd47064EfD36A7fB51dA3F8C5eb40c4cb4`

2021-04-01 16:05 UTC, JackieXu requested changes

2021-04-01 16:05 UTC, JackieXu commented on contracts/XSushiFeed.sol
> +            .div(10**18);
Think it's technically cleaner to call xSushi's decimals, but it doesn't change so it would also be silly. Just wanted to say it. :')

2021-04-01 16:05 UTC, JackieXu commented on deploy/25_xsushiFeed.js
> +    console.log("24. Deploy XSushi Feed")
24? Or 25? :)

2021-04-02 21:17 UTC, nourharidy commented on contracts/XSushiFeed.sol
> +interface Feed {
Ignored for consistency with `Oracle`

2021-04-02 21:18 UTC, nourharidy commented on deploy/25_xsushiFeed.js
> +    console.log("24. Deploy XSushi Feed")
fixed

2021-04-02 21:18 UTC, merged